[package]
name = "byor"
version = "2.0.1"
edition = "2024"
authors = ["Devin Droddy <devin@justdeeevin.dev"]
license = "MIT"
repository = "https://github.com/justdeeevin/byor"
description = "Bring your own runtime!"
readme = "README.md"
keywords = ["agnostic", "runtime", "tokio", "smol", "futures"]
categories = [
  "asynchronous",
  "concurrency",
  "filesystem",
  "network-programming",
  "rust-patterns",
]

[dependencies]
futures-core = { version = "0.3.34", optional = true }
futures-io = { version = "0.3.34", optional = true }
futures-util = { version = "0.3.34", optional = true }

tokio = { version = "1.53.2", optional = true, features = [
  "sync",
  "rt-multi-thread",
  "rt",
  "fs",
  "time",
  "net",
  "process",
] }
tokio-util = { version = "0.7.19", default-features = false, optional = true, features = [
  "rt",
  "compat",
] }
tokio-stream = { version = "0.1.19", default-features = false, optional = true, features = [
  "sync",
  "fs",
  "time",
  "net",
] }

futures = { version = "0.3.34", default-features = false, optional = true, features = [
  "thread-pool",
  "executor",
] }

smol = { version = "2.0.2", optional = true }

[features]
default = ["full"]

smol = ["dep:smol"]
tokio = ["dep:tokio", "dep:tokio-stream", "dep:tokio-util", "dep:futures-util"]
futures = ["dep:futures"]

full = ["lock", "channel", "exec", "fs", "fd", "time", "net", "process"]
lock = []
channel = ["dep:futures-core"]
exec = []
local-exec = []
fs = ["dep:futures-core", "dep:futures-io"]
fd = []
time = ["dep:futures-core"]
net = ["dep:futures-io"]
process = ["dep:futures-core", "dep:futures-io"]
